FROM node:11.15.0 as dev

ENV PATH $PATH:/usr/lib/node_modules/bin
RUN apt-get update && apt-get install --no-install-recommends -y python3-pip make build-essential python3-dev

WORKDIR /usr/app

COPY ./ /usr/app/
RUN npm ci

RUN pip3 install setuptools
RUN if [ -f src/python/requirements.txt ]; then pip3 install -r src/python/requirements.txt; fi

ENV PORT=3000

ENV DISPLAY=:0

CMD ["npx", "nodemon"]
