FROM node:11.15.0 AS build

RUN apt-get update && apt-get install -y python3-pip

COPY . /app/dir
WORKDIR /app/dir

RUN npm install
RUN npm run-script lint
RUN npm run-script compile

WORKDIR /app/dir/web
RUN npm ci
RUN npm run build
WORKDIR /app/dir
RUN npm run-script dist
