FROM node:15.3.0-buster-slim

ENV PATH $PATH:/usr/lib/node_modules/bin
RUN npm install -g ts-node@9.0.0 nodemon@2.0.6 typescript@4.0.3 && \
    apt-get update && apt-get install --no-install-recommends -y python3-pip make build-essential

WORKDIR /usr/app

COPY ./ /usr/app/
RUN npm ci

RUN pip3 install setuptools
RUN if [ -f src/python/requirements.txt ]; then pip3 install -r src/python/requirements.txt; fi

ENV PORT=3000

CMD nodemon
